### PR TITLE
Refresh package

### PR DESCRIPTION
**Pull request by Adamtaranto**
- Use Hatchling as build tool
- Use hatch-vcs to set version from git tag
- Allow install without mummer packages on path, mv checks to pymummer import.
- Replace setup.py with pyproject.toml
- update package structure
- Remove "nose", incompatible with newer python, use pytest

### CODE REVIEW

**Comment by Adamtaranto** [comment]
Should probably use github actions for CI testing (instead of Travis) and pushing to pypi. 

Need admin access for that.

**Comment by Adamtaranto** [comment]
Version is now set using git tags. 

Please bump the tag ~~to `0.7.0`~~ (without the "v" prefix) before running `hatch build` and cutting a new release / publishing to PyPi.

**Comment by martinghunt** [comment]
Oh wow, thanks for this :)

Yeah, definitely needs moving from travis to github actions, will try to do that soon. In the meantime I can make a new release 0.12.0 (I guess 0.7.0 was a typo?)

**Comment by Adamtaranto** [comment]
Ah yes, I wasn't looking at the full tag list. Thanks!

**Pull request merged**
